/**
 * Contest Atlas — directory.js
 * Curated Global Directory of Verified Literary Contests, Flash Prizes,
 * Nonfiction Awards, Top Journals, and Fellowships.
 * Last Automated Sync: 2026-09-25T02:26:05.542Z
 */

window.CONTEST_DIRECTORY = [
  {
    "id": "dir_sf_01",
    "name": "Iowa Short Fiction Award",
    "organization": "University of Iowa Press",
    "category": "Short Story",
    "type": "Writing Contest",
    "website": "https://uipress.uiowa.edu/iowa-short-fiction-award",
    "deadlineDate": "2026-11-30",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/Chicago",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 0,
    "prizeAmount": "$1,000 + Book Publication",
    "minWords": 30000,
    "maxWords": 75000,
    "blindJudging": true,
    "simultaneousAllowed": true,
    "unpublishedOnly": true,
    "reqFormat": "PDF",
    "reqBio": "prohibited",
    "reqCover": "optional",
    "rawGuidelines": "Manuscripts must be a collection of short stories in English of at least 150 pages. Work must not be previously published as a collection. Blind judging: no author name on manuscript."
  },
  {
    "id": "dir_sf_02",
    "name": "Ploughshares Emerging Writer's Contest",
    "organization": "Ploughshares / Emerson College",
    "category": "Short Story",
    "type": "Writing Contest",
    "website": "https://www.pshares.org/submit/emerging-writers-contest",
    "deadlineDate": "2026-05-15",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/New_York",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 24,
    "prizeAmount": "$2,000 + Publication",
    "minWords": 1000,
    "maxWords": 6000,
    "blindJudging": true,
    "simultaneousAllowed": true,
    "unpublishedOnly": true,
    "reqFormat": "DOCX",
    "reqBio": "optional",
    "reqCover": "optional",
    "rawGuidelines": "For writers who have not yet published a book of prose. Fiction entries should not exceed 6,000 words. Anonymous judging; remove author contact info."
  },
  {
    "id": "dir_sf_03",
    "name": "Zoetrope: All-Story Annual Fiction Contest",
    "organization": "Zoetrope: All-Story",
    "category": "Short Story",
    "type": "Writing Contest",
    "website": "https://www.all-story.com/contests/",
    "deadlineDate": "2026-10-01",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/Los_Angeles",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 30,
    "prizeAmount": "$1,000 (1st) / $500 (2nd) / $250 (3rd)",
    "minWords": 500,
    "maxWords": 5000,
    "blindJudging": true,
    "simultaneousAllowed": true,
    "unpublishedOnly": true,
    "reqFormat": "DOCX",
    "reqBio": "optional",
    "reqCover": "optional",
    "rawGuidelines": "All short fiction up to 5,000 words. Open to international submissions. Judged blindly by a guest judge. Previously unpublished work only."
  },
  {
    "id": "dir_sf_04",
    "name": "The Missouri Review Jeffrey E. Smith Editors' Prize",
    "organization": "The Missouri Review",
    "category": "Short Story",
    "type": "Writing Contest",
    "website": "https://www.missourireview.com/contests/jeffrey-e-smith-editors-prize/",
    "deadlineDate": "2026-10-01",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/Chicago",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 30,
    "prizeAmount": "$5,000 + Publication",
    "minWords": 1000,
    "maxWords": 8500,
    "blindJudging": true,
    "simultaneousAllowed": true,
    "unpublishedOnly": true,
    "reqFormat": "DOCX",
    "reqBio": "optional",
    "reqCover": "optional",
    "rawGuidelines": "Fiction entries up to 25 typed double-spaced pages (approx 8,500 words). Winner receives $5,000 and publication in The Missouri Review. Blind judging."
  },
  {
    "id": "dir_sf_05",
    "name": "Nelson Algren Short Story Award",
    "organization": "Chicago Tribune",
    "category": "Short Story",
    "type": "Writing Contest",
    "website": "https://www.chicagotribune.com/nelson-algren-literary-awards/",
    "deadlineDate": "2026-12-31",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/Chicago",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 0,
    "prizeAmount": "$3,500 (1st) / $1,000 (Finalists)",
    "minWords": 2000,
    "maxWords": 8000,
    "blindJudging": true,
    "simultaneousAllowed": true,
    "unpublishedOnly": true,
    "reqFormat": "DOCX",
    "reqBio": "prohibited",
    "reqCover": "optional",
    "rawGuidelines": "Free to enter short story contest for unpublished fiction. Up to 8,000 words. Strictly anonymous judging; all identifying text must be omitted."
  },
  {
    "id": "dir_sf_06",
    "name": "Bridport Prize — Short Story Award",
    "organization": "The Bridport Prize (UK)",
    "category": "Short Story",
    "type": "Writing Contest",
    "website": "https://bridportprize.org.uk/",
    "deadlineDate": "2026-05-31",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "Europe/London",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 14,
    "prizeAmount": "£5,000 (1st) / £1,000 (2nd) / £500 (3rd)",
    "minWords": 500,
    "maxWords": 4000,
    "blindJudging": true,
    "simultaneousAllowed": true,
    "unpublishedOnly": true,
    "reqFormat": "DOCX",
    "reqBio": "prohibited",
    "reqCover": "prohibited",
    "rawGuidelines": "Short stories up to 4,000 words on any theme. Strictly 100% anonymous reading. Do not put name or address on any page of the story."
  },
  {
    "id": "dir_sf_07",
    "name": "Pushcart Prize Nomination Window",
    "organization": "Pushcart Press",
    "category": "Short Story",
    "type": "Magazine / Periodical",
    "website": "https://www.pushcartprize.com/",
    "deadlineDate": "2026-12-01",
    "deadlineTime": "17:00",
    "deadlineTimeZone": "America/New_York",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 0,
    "prizeAmount": "Pushcart Anthology Inclusion",
    "minWords": 100,
    "maxWords": 10000,
    "blindJudging": false,
    "simultaneousAllowed": false,
    "unpublishedOnly": false,
    "reqFormat": "PDF",
    "reqBio": "required",
    "reqCover": "required",
    "rawGuidelines": "Nominations submitted by literary magazine editors for best work published in the preceding calendar year."
  },
  {
    "id": "dir_sf_08",
    "name": "Kenyon Review Short Fiction Contest",
    "organization": "The Kenyon Review",
    "category": "Short Story",
    "type": "Writing Contest",
    "website": "https://kenyonreview.org/contests/short-fiction/",
    "deadlineDate": "2026-01-31",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/New_York",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 24,
    "prizeAmount": "$1,000 + Publication",
    "minWords": 500,
    "maxWords": 1200,
    "blindJudging": true,
    "simultaneousAllowed": true,
    "unpublishedOnly": true,
    "reqFormat": "DOCX",
    "reqBio": "optional",
    "reqCover": "optional",
    "rawGuidelines": "Flash and short fiction up to 1,200 words. Open to writers who have not yet published a full-length book of fiction. Blind judging."
  },
  {
    "id": "dir_sf_09",
    "name": "CRAFT Short Fiction Prize",
    "organization": "CRAFT Literary",
    "category": "Short Story",
    "type": "Writing Contest",
    "website": "https://www.craftliterary.com/craft-short-fiction-prize/",
    "deadlineDate": "2026-09-15",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/Chicago",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 20,
    "prizeAmount": "$2,000 (1st) / $500 (2nd) / $300 (3rd)",
    "minWords": 1000,
    "maxWords": 5000,
    "blindJudging": true,
    "simultaneousAllowed": true,
    "unpublishedOnly": true,
    "reqFormat": "DOCX",
    "reqBio": "optional",
    "reqCover": "optional",
    "rawGuidelines": "Short fiction up to 5,000 words. Judged anonymously. International submissions welcome."
  },
  {
    "id": "dir_fl_01",
    "name": "SmokeLong Quarterly Micro Fellowship & Award",
    "organization": "SmokeLong Quarterly",
    "category": "Flash Fiction",
    "type": "Writing Contest",
    "website": "https://www.smokelong.com/smokelong-quarterly-micro-fellowship/",
    "deadlineDate": "2026-06-30",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/New_York",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 15,
    "prizeAmount": "$1,500 Fellowship + Publication",
    "minWords": 100,
    "maxWords": 400,
    "blindJudging": true,
    "simultaneousAllowed": true,
    "unpublishedOnly": true,
    "reqFormat": "DOCX",
    "reqBio": "optional",
    "reqCover": "optional",
    "rawGuidelines": "Micro fiction up to 400 words. Anonymous judging. Multiple pieces may be submitted in separate entries."
  },
  {
    "id": "dir_fl_02",
    "name": "Bath Flash Fiction Award",
    "organization": "Bath Flash Fiction (UK)",
    "category": "Flash Fiction",
    "type": "Writing Contest",
    "website": "https://www.bathflashfictionaward.com/",
    "deadlineDate": "2026-10-18",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "Europe/London",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 12,
    "prizeAmount": "£1,000 (1st) / £300 (2nd) / £100 (3rd)",
    "minWords": 50,
    "maxWords": 300,
    "blindJudging": true,
    "simultaneousAllowed": true,
    "unpublishedOnly": true,
    "reqFormat": "DOCX",
    "reqBio": "prohibited",
    "reqCover": "prohibited",
    "rawGuidelines": "Flash fiction up to 300 words. Strictly blind reading; any names or identifying text will disqualify entry."
  },
  {
    "id": "dir_fl_03",
    "name": "Fractured Lit Flash Fiction Prize",
    "organization": "Fractured Lit",
    "category": "Flash Fiction",
    "type": "Writing Contest",
    "website": "https://www.fracturedlit.com/prizes/",
    "deadlineDate": "2026-07-31",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/Chicago",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 20,
    "prizeAmount": "$3,000 (1st) / $1,000 (2nd) / $500 (3rd)",
    "minWords": 100,
    "maxWords": 1000,
    "blindJudging": true,
    "simultaneousAllowed": true,
    "unpublishedOnly": true,
    "reqFormat": "DOCX",
    "reqBio": "optional",
    "reqCover": "optional",
    "rawGuidelines": "Flash stories up to 1,000 words. Anonymous evaluation. Previously unpublished work only."
  },
  {
    "id": "dir_fl_04",
    "name": "Reflex Fiction Quarterly Flash Prize",
    "organization": "Reflex Fiction (UK)",
    "category": "Flash Fiction",
    "type": "Writing Contest",
    "website": "https://www.reflexfiction.com/",
    "deadlineDate": "2026-08-31",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "Europe/London",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 9,
    "prizeAmount": "£1,200 (1st) / £600 (2nd)",
    "minWords": 180,
    "maxWords": 360,
    "blindJudging": true,
    "simultaneousAllowed": true,
    "unpublishedOnly": true,
    "reqFormat": "TXT / Web Form",
    "reqBio": "prohibited",
    "reqCover": "prohibited",
    "rawGuidelines": "Between 180 and 360 words. Strict word count compliance. 100% blind judging."
  },
  {
    "id": "dir_fl_05",
    "name": "Wigleaf Top 50 Submission Window",
    "organization": "Wigleaf (Very Short Fiction)",
    "category": "Flash Fiction",
    "type": "Magazine / Periodical",
    "website": "https://wigleaf.com/",
    "deadlineDate": "2026-11-15",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/Chicago",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 0,
    "prizeAmount": "Wigleaf Top 50 Consideration",
    "minWords": 50,
    "maxWords": 1000,
    "blindJudging": false,
    "simultaneousAllowed": true,
    "unpublishedOnly": true,
    "reqFormat": "DOCX",
    "reqBio": "optional",
    "reqCover": "optional",
    "rawGuidelines": "Under 1,000 words. Free to submit. Simultaneous submissions allowed."
  },
  {
    "id": "dir_nf_01",
    "name": "Annie Dillard Award for Creative Nonfiction",
    "organization": "Bellingham Review",
    "category": "Essay / Nonfiction",
    "type": "Writing Contest",
    "website": "https://bhreview.org/contests/",
    "deadlineDate": "2026-12-01",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/Los_Angeles",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 20,
    "prizeAmount": "$1,000 + Publication",
    "minWords": 1500,
    "maxWords": 4000,
    "blindJudging": true,
    "simultaneousAllowed": true,
    "unpublishedOnly": true,
    "reqFormat": "DOCX",
    "reqBio": "optional",
    "reqCover": "optional",
    "rawGuidelines": "Personal essays, memoir snippets, literary journalism up to 4,000 words. Blind judging; remove author identifiers."
  },
  {
    "id": "dir_nf_02",
    "name": "CRAFT Creative Nonfiction Award",
    "organization": "CRAFT Literary",
    "category": "Essay / Nonfiction",
    "type": "Writing Contest",
    "website": "https://www.craftliterary.com/craft-creative-nonfiction-award/",
    "deadlineDate": "2026-06-30",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/Chicago",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 20,
    "prizeAmount": "$2,000 (1st) / $500 (2nd) / $300 (3rd)",
    "minWords": 1000,
    "maxWords": 6000,
    "blindJudging": true,
    "simultaneousAllowed": true,
    "unpublishedOnly": true,
    "reqFormat": "DOCX",
    "reqBio": "optional",
    "reqCover": "optional",
    "rawGuidelines": "Creative essays and memoir excerpts up to 6,000 words. Blind reading."
  },
  {
    "id": "dir_nf_03",
    "name": "Creative Nonfiction Magazine Essay Open Call",
    "organization": "Creative Nonfiction Foundation",
    "category": "Essay / Nonfiction",
    "type": "Magazine / Periodical",
    "website": "https://creativenonfiction.org/submissions/",
    "deadlineDate": "2026-10-31",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/New_York",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 3,
    "prizeAmount": "$1,000 upon publication",
    "minWords": 2000,
    "maxWords": 4500,
    "blindJudging": false,
    "simultaneousAllowed": true,
    "unpublishedOnly": true,
    "reqFormat": "DOCX",
    "reqBio": "required",
    "reqCover": "required",
    "rawGuidelines": "Longform creative nonfiction essays between 2,000 and 4,500 words. Include short author bio and cover statement."
  },
  {
    "id": "dir_nf_04",
    "name": "Hippocampus Magazine Remember in November Contest",
    "organization": "Hippocampus Magazine",
    "category": "Essay / Nonfiction",
    "type": "Writing Contest",
    "website": "https://hippocampusmagazine.com/contest/",
    "deadlineDate": "2026-09-15",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/New_York",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 15,
    "prizeAmount": "$1,000 (1st) / $250 (Finalists)",
    "minWords": 1000,
    "maxWords": 3500,
    "blindJudging": true,
    "simultaneousAllowed": true,
    "unpublishedOnly": true,
    "reqFormat": "DOCX",
    "reqBio": "prohibited",
    "reqCover": "optional",
    "rawGuidelines": "Memoir and personal essays under 3,500 words. Blind judging; no name on manuscript."
  },
  {
    "id": "dir_jm_01",
    "name": "The Paris Review General Fiction",
    "organization": "The Paris Review",
    "category": "Short Story",
    "type": "Magazine / Periodical",
    "website": "https://www.theparisreview.org/about/submissions",
    "deadlineDate": "2026-10-31",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/New_York",
    "rolling": true,
    "annualRecurring": true,
    "feeAmount": 0,
    "prizeAmount": "Standard Professional Word Rate",
    "minWords": 1500,
    "maxWords": 10000,
    "blindJudging": false,
    "simultaneousAllowed": true,
    "unpublishedOnly": true,
    "reqFormat": "DOCX",
    "reqBio": "optional",
    "reqCover": "optional",
    "rawGuidelines": "Short fiction of any length or subject. Free submission window via Submittable. Simultaneous submissions accepted."
  },
  {
    "id": "dir_jm_02",
    "name": "One Story Open Reading Period",
    "organization": "One Story Inc.",
    "category": "Short Story",
    "type": "Magazine / Periodical",
    "website": "https://one-story.com/submissions/",
    "deadlineDate": "2026-11-14",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/New_York",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 0,
    "prizeAmount": "$500 + 25 Author Copies",
    "minWords": 3000,
    "maxWords": 8000,
    "blindJudging": false,
    "simultaneousAllowed": false,
    "unpublishedOnly": true,
    "reqFormat": "DOCX",
    "reqBio": "required",
    "reqCover": "required",
    "rawGuidelines": "Single short stories between 3,000 and 8,000 words. No simultaneous submissions permitted. Unpublished work only."
  },
  {
    "id": "dir_jm_03",
    "name": "Virginia Quarterly Review (VQR)",
    "organization": "University of Virginia",
    "category": "Short Story",
    "type": "Magazine / Periodical",
    "website": "https://www.vqronline.org/about-vqr/submissions",
    "deadlineDate": "2026-07-31",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/New_York",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 3,
    "prizeAmount": "$1,000+ ($0.25/word)",
    "minWords": 2000,
    "maxWords": 7500,
    "blindJudging": false,
    "simultaneousAllowed": true,
    "unpublishedOnly": true,
    "reqFormat": "DOCX",
    "reqBio": "required",
    "reqCover": "optional",
    "rawGuidelines": "Literary short fiction and essays. Simultaneous submissions allowed, notify immediately if accepted elsewhere."
  },
  {
    "id": "dir_jm_04",
    "name": "Granta Magazine Open Call",
    "organization": "Granta Publications (UK)",
    "category": "Short Story",
    "type": "Magazine / Periodical",
    "website": "https://granta.com/submissions/",
    "deadlineDate": "2026-10-15",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "Europe/London",
    "rolling": true,
    "annualRecurring": true,
    "feeAmount": 4,
    "prizeAmount": "Competitive Professional Rate",
    "minWords": 1500,
    "maxWords": 6000,
    "blindJudging": false,
    "simultaneousAllowed": true,
    "unpublishedOnly": true,
    "reqFormat": "DOCX",
    "reqBio": "required",
    "reqCover": "required",
    "rawGuidelines": "Contemporary fiction and narrative nonfiction. Up to 6,000 words."
  },
  {
    "id": "dir_fel_01",
    "name": "Wallace Stegner Fellowship in Creative Writing",
    "organization": "Stanford University",
    "category": "Fellowship",
    "type": "Fellowship",
    "website": "https://creativewriting.stanford.edu/fellowships/stegner-fellowship",
    "deadlineDate": "2026-11-30",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/Los_Angeles",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 85,
    "prizeAmount": "$50,000/yr Living Stipend (2-Year Fellowship)",
    "minWords": 5000,
    "maxWords": 9000,
    "blindJudging": false,
    "simultaneousAllowed": true,
    "unpublishedOnly": false,
    "reqFormat": "PDF",
    "reqBio": "required",
    "reqCover": "required",
    "rawGuidelines": "Two-year fellowship at Stanford. Prose manuscript of up to 9,000 words (or 2-3 stories). Full CV and cover statement required."
  },
  {
    "id": "dir_fel_02",
    "name": "Fine Arts Work Center Writing Fellowship",
    "organization": "Fine Arts Work Center (FAWC) Provincetown",
    "category": "Fellowship",
    "type": "Fellowship",
    "website": "https://fawc.org/fellowship/",
    "deadlineDate": "2026-12-15",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/New_York",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 65,
    "prizeAmount": "7-Month Residency + Monthly Stipend",
    "minWords": 4000,
    "maxWords": 8500,
    "blindJudging": true,
    "simultaneousAllowed": true,
    "unpublishedOnly": false,
    "reqFormat": "PDF",
    "reqBio": "required",
    "reqCover": "required",
    "rawGuidelines": "Seven-month residency in Provincetown, MA for emerging writers. Fiction submission sample up to 35 double-spaced pages. Blind review of writing sample."
  },
  {
    "id": "dir_fel_03",
    "name": "MacDowell Artist Residency Fellowship",
    "organization": "The MacDowell Colony",
    "category": "Fellowship",
    "type": "Fellowship",
    "website": "https://www.macdowell.org/apply",
    "deadlineDate": "2026-09-10",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/New_York",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 30,
    "prizeAmount": "Full Fellowship & Studio Residency",
    "minWords": 3000,
    "maxWords": 6000,
    "blindJudging": true,
    "simultaneousAllowed": true,
    "unpublishedOnly": false,
    "reqFormat": "PDF",
    "reqBio": "required",
    "reqCover": "required",
    "rawGuidelines": "Prose writing sample up to 25 pages. All work reviewed anonymously by peer panel."
  },
  {
    "id": "dir_fel_04",
    "name": "NEA Literature Fellowship for Creative Writers",
    "organization": "National Endowment for the Arts",
    "category": "Fellowship",
    "type": "Fellowship",
    "website": "https://www.arts.gov/grants/creative-writing-fellowships",
    "deadlineDate": "2026-03-12",
    "deadlineTime": "23:59",
    "deadlineTimeZone": "America/New_York",
    "rolling": false,
    "annualRecurring": true,
    "feeAmount": 0,
    "prizeAmount": "$25,000 Individual Artist Grant",
    "minWords": 4000,
    "maxWords": 7500,
    "blindJudging": true,
    "simultaneousAllowed": true,
    "unpublishedOnly": false,
    "reqFormat": "PDF",
    "reqBio": "required",
    "reqCover": "required",
    "rawGuidelines": "Individual grant for published creative prose writers. Writing sample up to 25 pages. Blind evaluation of manuscript."
  }
];
